kind: Service
apiVersion: v1
metadata:
  name: lastmile-cluster
spec:
  type: NodePort
  selector:
    app: lastmile-cluster
  ports:
    - protocol: TCP
      name: management
      port: 8558
      targetPort: management
    - protocol: TCP
      name: api
      port: 8080
      targetPort: api