apiVersion: apps/v1
kind: Deployment
metadata:
  name: passenger-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passenger-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: passenger-app
    spec:
      containers:
        - image: lastmile/passenger-app:0.1.0
          imagePullPolicy: Never
          name: passenger-app
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          ports:
            - name: remoting
              containerPort: 2552
            - name: api
              containerPort: 8080
            - name: management
              containerPort: 8558
          readinessProbe:
            tcpSocket:
              port: 8558
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8558
            initialDelaySeconds: 15
            periodSeconds: 20

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
subjects:
  # Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
  # For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
  - kind: User
    name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io